### ISSUE TITLE
How to generate my own preprocessed dataset as your given CUHK-PEDES?

### ISSUE THREAD

**Issue by medivhna** [BrandonHanx/TextReID#2]
We hope to implement this project on our own dataset. But there's no detail on the preprocessing on the dataset.

**Comment by BrandonHanx** [comment]
Hello, I cannot find the original script to generate the exact same vocab file as shared in Google Drive coz it has been quite a long time.

But I prepared [another notebook](https://drive.google.com/file/d/1fM8NbDwShW_elrgVihFskQm_ELbmVG0q/view?usp=sharing) to make an example of how to do preprocessing. I wish this notebook can help you.

The main idea is:
1. use a tokenizer to tokenize all sentences in the original dataset so that we can have a vocab file
2. (optional) you can do spell check for this vocab
3. feed each token to a pretrained language model (e.g. CLIP text encoder) to get the word embedding and then write them into a *.npy file

**Comment by BrandonHanx** [comment]
I assume the issue has been resolved. Feel free to reopen if there is any problem.
